// <auto-generated />
using FarmaciaElPalenque.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FarmaciaElPalenque.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250623183517_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FarmaciaElPalenque.Models.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Medicamentos"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Perfumería"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Cuidado personal"
                        });
                });

            modelBuilder.Entity("FarmaciaElPalenque.Models.Productos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("categoriaId")
                        .HasColumnType("int");

                    b.Property<string>("imagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("categoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Stock = 100,
                            categoriaId = 1,
                            imagenUrl = "https://www.anikashop.com.ar/product_images/w/994/8024587__72227_zoom.jpg",
                            nombre = "Bayaspirina",
                            precio = 5728m
                        },
                        new
                        {
                            id = 2,
                            Stock = 100,
                            categoriaId = 1,
                            imagenUrl = "https://www.centraloeste.com.ar/media/catalog/product/cache/9c821fce06d7004f361a4c419f8b1787/7/7/7790839980453.png",
                            nombre = "Ibu400",
                            precio = 15000m
                        },
                        new
                        {
                            id = 3,
                            Stock = 100,
                            categoriaId = 2,
                            imagenUrl = "https://www.casaflorian.com.ar/wp-content/uploads/2023/03/391-525-01_C.jpg",
                            nombre = "Shampoo Pantene",
                            precio = 20000m
                        },
                        new
                        {
                            id = 4,
                            Stock = 100,
                            categoriaId = 3,
                            imagenUrl = "https://industriaslitoral.com.ar/wp-content/uploads/2022/05/3011150_f.jpg",
                            nombre = "Jabón Rexona",
                            precio = 5000m
                        });
                });

            modelBuilder.Entity("FarmaciaElPalenque.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            apellido = "General",
                            email = "admin@palenque.com",
                            nombre = "admin",
                            passwordHash = "admin123",
                            rol = "Administrador"
                        },
                        new
                        {
                            id = 2,
                            apellido = "Perez",
                            email = "juan@correo.com",
                            nombre = "Juan",
                            passwordHash = "1234",
                            rol = "Cliente"
                        },
                        new
                        {
                            id = 3,
                            apellido = "Garcia",
                            email = "maria@correo.com",
                            nombre = "Maria",
                            passwordHash = "clave123",
                            rol = "Cliente"
                        },
                        new
                        {
                            id = 4,
                            apellido = "Lopez",
                            email = "carlos@correo.com",
                            nombre = "Carlos",
                            passwordHash = "qwerty",
                            rol = "Cliente"
                        },
                        new
                        {
                            id = 5,
                            apellido = "Gonzalez",
                            email = "laura@correo.com",
                            nombre = "Laura",
                            passwordHash = "pass1234",
                            rol = "Cliente"
                        },
                        new
                        {
                            id = 6,
                            apellido = "Fernandez",
                            email = "ana@correo.com",
                            nombre = "Ana",
                            passwordHash = "abc123",
                            rol = "Cliente"
                        },
                        new
                        {
                            id = 7,
                            apellido = "Alvarez",
                            email = "roberto@palenque.com",
                            nombre = "Roberto",
                            passwordHash = "adminadmin",
                            rol = "Administrador"
                        },
                        new
                        {
                            id = 8,
                            apellido = "Martinez",
                            email = "camila@correo.com",
                            nombre = "Camila",
                            passwordHash = "cami321",
                            rol = "Cliente"
                        },
                        new
                        {
                            id = 9,
                            apellido = "Ruiz",
                            email = "luciano@correo.com",
                            nombre = "Luciano",
                            passwordHash = "123456",
                            rol = "Cliente"
                        },
                        new
                        {
                            id = 10,
                            apellido = "Mendez",
                            email = "carolina@correo.com",
                            nombre = "Carolina",
                            passwordHash = "securepass",
                            rol = "Cliente"
                        });
                });

            modelBuilder.Entity("FarmaciaElPalenque.Models.Productos", b =>
                {
                    b.HasOne("FarmaciaElPalenque.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FarmaciaElPalenque.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
